//EJERCICIO 1
var agua = "Tamarindo";

switch (agua) {
    case "Tamarindo":
        console.log("El agua de tamarindo sabe chida");
        break;
}
//EJERCICIO 2
var refresco = "Limon";
switch (refresco) {
    case "Limon":
        console.log("El refresco de limon sabe chido");
        break;
}
//EJERCICIO 3
var pescado = "Azul";
switch (pescado) {
    case "Azul":
        console.log("Tengo un pescado azul");
        break;
}
//EJERCICIO 4
var Naruto = "Rubio";
switch (Naruto) {
    case "Rubio":
        console.log("Naruto es rubio");
        break;
}
//EJERCICIO 5
var OnePiece = "Besto Shonen";
switch (OnePiece) {
    case "Besto Shonen":
        console.log("One Piece es el mejor anime")
        break;
}