//EJERCICIO 1
var futbol = "soccer";
switch (futbol) {
    case "soccer":
        if (futbol == "balon") {
            console.log("futbol soccer");
        } else {
            console.log("Basquetbol");
            break;
        }
}
//EJERCICIO 2
var xbox = "Halo";
var playstation = "GOW";
switch (xbox) {
    case "Halo":
        if (playstation == "GOW") {
            console.log("Te amo Xbox");
        } else {
            console.log("Te amo Playstation");
            break;
        }
}
//EJERCICIO 3
var universidad = "UPT";
var preparatoria = "CBT2";
switch (preparatoria) {
    case "CBT2":
        if (preparatoria == "UPT") {
            console.log("Extraño la preparatoria");
        } else {
            console.log("Extraño a mi ex");
            break;
        }
}
//EJERCICIO 4
var PERRO = "PASTOR";
var GATO = "MIAU";
switch (PERRO) {
    case "PASTOR":
        if (PERRO == "PASTOR") {
            console.log("Mi perro se llama Jack");
        } else {
            console.log("No tengo gatos");
            break;
        }
}
//EJERCICIO 5
var Bonafont = "Levite";
var Epura = "Agualigeraxd";
switch (Bonafont) {
    case "Levite":
        if (Epura == "Agualigeraxd") {
            console.log("Tengo Hambre");
        } else {
            console.log("Tengo sed");
            break;
        }
}